name: Generate Daily Report

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main # Runs when commits are pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Report Generator
        run: python generate_report.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update daily status report" || echo "No changes to commit"
          git push
